### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dsakura** [aprikyan/google-books-downloader#15]
Traceback (most recent call last):
  File "C:\google-books-downloader\gbd.py", line 244, in <module>
    driver = webdriver.Chrome("chromedriver.exe", options=chrome_options)
  File "C:\Python39\lib\site-packages\seleniumwire\webdriver.py", line 211, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by dsakura** [comment]
Fixed with the right chromedriver, but with new error:

```
Traceback (most recent call last):
  File "C:\google-books-downloader\gbd.py", line 248, in <module>
    step2()
  File "C:\google-books-downloader\gbd.py", line 216, in step2
    cookie = get_cookie(list(all_pages.items())[0][1])
  File "C:\google-books-downloader\gbd.py", line 140, in get_cookie
    return cookies[0]
IndexError: list index out of range
```
Thanks!
